name: Dynamic Analysis

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install dependencies
            run: yarn install --frozen-lockfile --non-interactive --production=false

          - name: Run ESLint check
            run: yarn test:coverage
