name: preview
on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    env:
      EXPO_PUBLIC_API_BASE_URL: ${{ vars.EXPO_PUBLIC_API_BASE_URL }}
      EXPO_PUBLIC_QNA_API_BASE_URL: ${{ vars.EXPO_PUBLIC_QNA_API_BASE_URL }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets."
            exit 1
          fi
      - name: Check for ENV variables
        run: |
          if [ -z "${{ vars.EXPO_PUBLIC_API_BASE_URL }}" ]; then
            echo "EXPO_PUBLIC_API_BASE_URL is not set"
            exit 1
          fi
          if [ -z "${{ vars.EXPO_PUBLIC_QNA_API_BASE_URL }}" ]; then
            echo "EXPO_PUBLIC_QNA_API_BASE_URL is not set"
            exit 1
          fi
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto
